[libraries]
assertj-core='org.assertj:assertj-core:3.26.0'
httpclient5="org.apache.httpcomponents.client5:httpclient5:5.3.1"
junit-bom='org.junit:junit-bom:5.10.4'
kerby='org.apache.kerby:kerb-simplekdc:2.0.3'
mockito-bom='org.mockito:mockito-bom:5.12.0'
okhttp3='com.squareup.okhttp3:okhttp:3.14.9'
okhttp3-mockwebserver='com.squareup.okhttp3:mockwebserver:3.14.9'
servlet-api='jakarta.servlet:jakarta.servlet-api:6.0.0'
spring-framework-bom='org.springframework:spring-framework-bom:6.1.8'
spring-security-bom='org.springframework.security:spring-security-bom:6.3.3'

[plugins]
spring-boot='org.springframework.boot:3.3.0'
dependency-management='io.spring.dependency-management:1.1.7'
security-release='io.spring.security.release:1.0.3'